### ISSUE TITLE
Simple Processing of Google Analytics Data

### ISSUE THREAD

**Issue by dpboam** [open-innovations/leeds-digital-festival-data#15]
### Tasks
- [x] Read downloaded GA data csv file (or files) from working directory
- [x] Process according to following rules
    - [x] Remove initial lines from file
    - [x] Use the date column as an index, and define as a proper date
    - [x] Fill in / handle null values - replace with NaN in pandas
    - [x] Re-format header names to lowercase and replace  " " with "_"
    - [x] Read in numbers using the commas argument in pandas
- [x] Combine new data with existing data using `pandas.combine_first` to add / update previously saved data.
- [x] Write file to `data/social` directory named `website.csv`.
- [x] Create summary files and save in `src/_data/metrics/website/`
    - [ ] Aggregate values based on month (per Twitter)
- [ ] Create simple webpage which dumps the content of the metrics object at url `/metrics/website/`

**Comment by gilesdring** [comment]
[webzite_stats.zip](https://github.com/open-innovations/leeds-digital-festival-data/files/9656920/webzite_stats.zip)
